#pragma once

#ifndef H_COLLISION
#define H_COLLISION

enum entityCategory
{
	BOUNDARY = 0x0001,
	FRIENDLY_PLAYER = 0x0002,
	ENEMY_PLAYER = 0x0004,
	FRIENDLY_ARROW = 0x0008,
	ENEMY_ARROW = 0x0010,
	ALL = BOUNDARY | FRIENDLY_PLAYER | ENEMY_PLAYER | FRIENDLY_ARROW | ENEMY_ARROW,
};

#endif